/**
 * Achievement Definitions
 * All achievement configurations and conditions
 */

import {
  FaSeedling,
  FaBookOpen,
  FaBullseye,
  FaCrown,
  FaFire,
  FaStar,
  FaTrophy,
  FaCheckCircle,
  FaBrain,
  FaClock,
  FaBolt,
  FaCrosshairs,
  FaGraduationCap,
  FaCertificate,
  FaCalendarAlt,
  FaGem,
  FaMedal,
  FaAward,
  FaRocket,
  FaHeart,
  FaSun,
  FaMoon,
  FaCompass,
  FaSpellCheck,
  FaEdit,
  FaLanguage,
  FaList,
  FaRobot,
} from "react-icons/fa";

export const ACHIEVEMENT_CATEGORIES = {
  LEARNING: 'learning',
  PRACTICE: 'practice',
  QUIZ: 'quiz',
  STREAK: 'streak',
  TRANSLATION: 'translation',
  SPEED: 'speed',
  ACCURACY: 'accuracy',
  DAILY_LOGIN: 'daily_login',
  COMPLETION: 'completion',
  XP_MILESTONES: 'xp_milestones',
  SPECIAL: 'special',
};

export const ACHIEVEMENTS = [
  // ==================== LEARNING (10) ====================
  {
    id: 'first_lesson',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: 'First Lesson',
    description: 'Complete your first lesson',
    icon: FaSeedling,
    condition: (stats) => stats.notesRead >= 1,
    xp: 50,
    rarity: 'common',
  },
  {
    id: '10_lessons',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: '10 Lessons',
    description: 'Complete 10 lessons',
    icon: FaBookOpen,
    condition: (stats) => stats.notesRead >= 10,
    xp: 100,
    rarity: 'common',
  },
  {
    id: '50_lessons',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: '50 Lessons',
    description: 'Complete 50 lessons',
    icon: FaBookOpen,
    condition: (stats) => stats.notesRead >= 50,
    xp: 200,
    rarity: 'uncommon',
  },
  {
    id: '100_lessons',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: '100 Lessons',
    description: 'Complete 100 lessons',
    icon: FaGraduationCap,
    condition: (stats) => stats.notesRead >= 100,
    xp: 500,
    rarity: 'rare',
  },
  {
    id: 'bookworm',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: 'Bookworm',
    description: 'Read 20 lessons in a single day',
    icon: FaBookOpen,
    condition: (stats) => stats.lessonsToday >= 20,
    xp: 150,
    rarity: 'uncommon',
  },
  {
    id: 'grammar_beginner',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: 'Grammar Beginner',
    description: 'Complete all Beginner topics',
    icon: FaSeedling,
    condition: (stats) => stats.beginnerTopicsCompleted >= stats.totalBeginnerTopics,
    xp: 300,
    rarity: 'rare',
  },
  {
    id: 'grammar_intermediate',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: 'Grammar Intermediate',
    description: 'Complete all Intermediate topics',
    icon: FaBookOpen,
    condition: (stats) => stats.intermediateTopicsCompleted >= stats.totalIntermediateTopics,
    xp: 400,
    rarity: 'rare',
  },
  {
    id: 'grammar_advanced',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: 'Grammar Advanced',
    description: 'Complete all Advanced topics',
    icon: FaBullseye,
    condition: (stats) => stats.advancedTopicsCompleted >= stats.totalAdvancedTopics,
    xp: 500,
    rarity: 'epic',
  },
  {
    id: 'grammar_master',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: 'Grammar Master',
    description: 'Complete all Master topics',
    icon: FaCrown,
    condition: (stats) => stats.masterTopicsCompleted >= stats.totalMasterTopics,
    xp: 1000,
    rarity: 'legendary',
  },
  {
    id: 'completionist',
    category: ACHIEVEMENT_CATEGORIES.LEARNING,
    title: 'Completionist',
    description: 'Complete 100% of all topics',
    icon: FaCertificate,
    condition: (stats) => stats.overallCompletion === 100,
    xp: 2000,
    rarity: 'legendary',
  },

  // ==================== QUIZ (8) ====================
  {
    id: 'first_quiz',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: 'First Quiz',
    description: 'Complete your first quiz',
    icon: FaBrain,
    condition: (stats) => stats.quizzesCompleted >= 1,
    xp: 50,
    rarity: 'common',
  },
  {
    id: '10_quizzes',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: '10 Quizzes',
    description: 'Complete 10 quizzes',
    icon: FaBrain,
    condition: (stats) => stats.quizzesCompleted >= 10,
    xp: 100,
    rarity: 'common',
  },
  {
    id: '50_quizzes',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: '50 Quizzes',
    description: 'Complete 50 quizzes',
    icon: FaBrain,
    condition: (stats) => stats.quizzesCompleted >= 50,
    xp: 250,
    rarity: 'uncommon',
  },
  {
    id: '100_quizzes',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: 'Quiz Master',
    description: 'Complete 100 quizzes',
    icon: FaTrophy,
    condition: (stats) => stats.quizzesCompleted >= 100,
    xp: 500,
    rarity: 'rare',
  },
  {
    id: 'perfect_quiz',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: 'Perfect Score',
    description: 'Get 100% on a quiz',
    icon: FaStar,
    condition: (stats) => stats.perfectQuizzes >= 1,
    xp: 100,
    rarity: 'uncommon',
  },
  {
    id: '5_perfect_quizzes',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: 'Perfectionist',
    description: 'Get 100% on 5 quizzes',
    icon: FaStar,
    condition: (stats) => stats.perfectQuizzes >= 5,
    xp: 200,
    rarity: 'rare',
  },
  {
    id: 'quiz_streak',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: 'Quiz Streak',
    description: 'Complete 10 quizzes in a row',
    icon: FaBolt,
    condition: (stats) => stats.quizStreak >= 10,
    xp: 300,
    rarity: 'epic',
  },
  {
    id: 'speed_demon',
    category: ACHIEVEMENT_CATEGORIES.QUIZ,
    title: 'Speed Demon',
    description: 'Complete a quiz in under 30 seconds',
    icon: FaBolt,
    condition: (stats) => stats.fastestQuizTime <= 30,
    xp: 150,
    rarity: 'uncommon',
  },

  // ==================== PRACTICE (8) ====================
  {
    id: 'first_practice',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'First Practice',
    description: 'Complete your first practice exercise',
    icon: FaCheckCircle,
    condition: (stats) => stats.practiceCompleted >= 1,
    xp: 50,
    rarity: 'common',
  },
  {
    id: '25_practice',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'Practice Makes Perfect',
    description: 'Complete 25 practice exercises',
    icon: FaCheckCircle,
    condition: (stats) => stats.practiceCompleted >= 25,
    xp: 150,
    rarity: 'uncommon',
  },
  {
    id: '100_practice',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'Practice Champion',
    description: 'Complete 100 practice exercises',
    icon: FaMedal,
    condition: (stats) => stats.practiceCompleted >= 100,
    xp: 400,
    rarity: 'rare',
  },
  {
    id: 'fill_blank_master',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'Fill in the Blank Master',
    description: 'Complete 50 fill in the blank exercises',
    icon: FaEdit,
    condition: (stats) => stats.fillBlankCompleted >= 50,
    xp: 200,
    rarity: 'uncommon',
  },
  {
    id: 'translation_master',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'Translation Master',
    description: 'Complete 50 translation exercises',
    icon: FaLanguage,
    condition: (stats) => stats.translationCompleted >= 50,
    xp: 200,
    rarity: 'uncommon',
  },
  {
    id: 'sentence_master',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'Sentence Master',
    description: 'Complete 50 sentence correction exercises',
    icon: FaSpellCheck,
    condition: (stats) => stats.sentenceCorrectionCompleted >= 50,
    xp: 200,
    rarity: 'uncommon',
  },
  {
    id: 'verb_master',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'Verb Master',
    description: 'Complete 50 verb form exercises',
    icon: FaList,
    condition: (stats) => stats.verbFormsCompleted >= 50,
    xp: 200,
    rarity: 'uncommon',
  },
  {
    id: 'ai_practitioner',
    category: ACHIEVEMENT_CATEGORIES.PRACTICE,
    title: 'AI Practitioner',
    description: 'Complete 10 AI practice sessions',
    icon: FaRobot,
    condition: (stats) => stats.aiPracticeCompleted >= 10,
    xp: 300,
    rarity: 'rare',
  },

  // ==================== STREAK (6) ====================
  {
    id: '3_day_streak',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    title: '3 Day Streak',
    description: 'Maintain a 3-day learning streak',
    icon: FaFire,
    condition: (stats) => stats.currentStreak >= 3,
    xp: 75,
    rarity: 'common',
  },
  {
    id: '7_day_streak',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    title: 'Week Warrior',
    description: 'Maintain a 7-day learning streak',
    icon: FaFire,
    condition: (stats) => stats.currentStreak >= 7,
    xp: 150,
    rarity: 'uncommon',
  },
  {
    id: '30_day_streak',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    title: 'Monthly Master',
    description: 'Maintain a 30-day learning streak',
    icon: FaFire,
    condition: (stats) => stats.currentStreak >= 30,
    xp: 500,
    rarity: 'rare',
  },
  {
    id: '100_day_streak',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    title: 'Century Streak',
    description: 'Maintain a 100-day learning streak',
    icon: FaFire,
    condition: (stats) => stats.currentStreak >= 100,
    xp: 1500,
    rarity: 'epic',
  },
  {
    id: 'longest_streak_10',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    title: 'Dedicated Learner',
    description: 'Achieve a 10-day longest streak',
    icon: FaAward,
    condition: (stats) => stats.longestStreak >= 10,
    xp: 200,
    rarity: 'uncommon',
  },
  {
    id: 'longest_streak_50',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    title: 'Legendary Streak',
    description: 'Achieve a 50-day longest streak',
    icon: FaAward,
    condition: (stats) => stats.longestStreak >= 50,
    xp: 750,
    rarity: 'epic',
  },

  // ==================== XP MILESTONES (8) ====================
  {
    id: '100_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '100 XP',
    description: 'Earn 100 total XP',
    icon: FaStar,
    condition: (stats) => stats.totalXP >= 100,
    xp: 0,
    rarity: 'common',
  },
  {
    id: '500_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '500 XP',
    description: 'Earn 500 total XP',
    icon: FaStar,
    condition: (stats) => stats.totalXP >= 500,
    xp: 0,
    rarity: 'common',
  },
  {
    id: '1000_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '1000 XP',
    description: 'Earn 1000 total XP',
    icon: FaStar,
    condition: (stats) => stats.totalXP >= 1000,
    xp: 0,
    rarity: 'uncommon',
  },
  {
    id: '2500_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '2500 XP',
    description: 'Earn 2500 total XP',
    icon: FaStar,
    condition: (stats) => stats.totalXP >= 2500,
    xp: 0,
    rarity: 'rare',
  },
  {
    id: '5000_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '5000 XP',
    description: 'Earn 5000 total XP',
    icon: FaStar,
    condition: (stats) => stats.totalXP >= 5000,
    xp: 0,
    rarity: 'epic',
  },
  {
    id: '10000_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '10000 XP',
    description: 'Earn 10000 total XP',
    icon: FaGem,
    condition: (stats) => stats.totalXP >= 10000,
    xp: 0,
    rarity: 'legendary',
  },
  {
    id: '25000_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '25000 XP',
    description: 'Earn 25000 total XP',
    icon: FaGem,
    condition: (stats) => stats.totalXP >= 25000,
    xp: 0,
    rarity: 'legendary',
  },
  {
    id: '50000_xp',
    category: ACHIEVEMENT_CATEGORIES.XP_MILESTONES,
    title: '50000 XP',
    description: 'Earn 50000 total XP',
    icon: FaGem,
    condition: (stats) => stats.totalXP >= 50000,
    xp: 0,
    rarity: 'mythic',
  },

  // ==================== DAILY LOGIN (4) ====================
  {
    id: 'early_bird',
    category: ACHIEVEMENT_CATEGORIES.DAILY_LOGIN,
    title: 'Early Bird',
    description: 'Login before 8 AM',
    icon: FaSun,
    condition: (stats) => stats.earlyLogins >= 1,
    xp: 50,
    rarity: 'common',
  },
  {
    id: 'night_owl',
    category: ACHIEVEMENT_CATEGORIES.DAILY_LOGIN,
    title: 'Night Owl',
    description: 'Login after 10 PM',
    icon: FaMoon,
    condition: (stats) => stats.lateLogins >= 1,
    xp: 50,
    rarity: 'common',
  },
  {
    id: 'consistent_learner',
    category: ACHIEVEMENT_CATEGORIES.DAILY_LOGIN,
    title: 'Consistent Learner',
    description: 'Login for 7 consecutive days',
    icon: FaCalendarAlt,
    condition: (stats) => stats.currentStreak >= 7,
    xp: 100,
    rarity: 'uncommon',
  },
  {
    id: 'dedicated_learner',
    category: ACHIEVEMENT_CATEGORIES.DAILY_LOGIN,
    title: 'Dedicated Learner',
    description: 'Login for 30 consecutive days',
    icon: FaCalendarAlt,
    condition: (stats) => stats.currentStreak >= 30,
    xp: 300,
    rarity: 'rare',
  },

  // ==================== SPECIAL (6) ====================
  {
    id: 'explorer',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    title: 'Explorer',
    description: 'Try all types of exercises',
    icon: FaCompass,
    condition: (stats) => 
      stats.fillBlankCompleted >= 1 &&
      stats.translationCompleted >= 1 &&
      stats.sentenceCorrectionCompleted >= 1 &&
      stats.verbFormsCompleted >= 1,
    xp: 200,
    rarity: 'uncommon',
  },
  {
    id: 'champion',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    title: 'Champion',
    description: 'Reach Master level',
    icon: FaTrophy,
    condition: (stats) => stats.level >= 10,
    xp: 1000,
    rarity: 'legendary',
  },
  {
    id: 'first_steps',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    title: 'First Steps',
    description: 'Complete your first activity',
    icon: FaRocket,
    condition: (stats) => stats.totalActivities >= 1,
    xp: 25,
    rarity: 'common',
  },
  {
    id: 'rising_star',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    title: 'Rising Star',
    description: 'Reach Level 5',
    icon: FaStar,
    condition: (stats) => stats.level >= 5,
    xp: 250,
    rarity: 'uncommon',
  },
  {
    id: 'overachiever',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    title: 'Overachiever',
    description: 'Unlock 50 achievements',
    icon: FaAward,
    condition: (stats) => stats.achievementsUnlocked >= 50,
    xp: 500,
    rarity: 'epic',
  },
  {
    id: 'legend',
    category: ACHIEVEMENT_CATEGORIES.SPECIAL,
    title: 'Legend',
    description: 'Unlock all achievements',
    icon: FaCrown,
    condition: (stats) => stats.achievementsUnlocked >= ACHIEVEMENTS.length,
    xp: 5000,
    rarity: 'mythic',
  },
];

export const RARITY_CONFIG = {
  common: { color: '#9CA3AF', label: 'Common' },
  uncommon: { color: '#10B981', label: 'Uncommon' },
  rare: { color: '#3B82F6', label: 'Rare' },
  epic: { color: '#8B5CF6', label: 'Epic' },
  legendary: { color: '#F59E0B', label: 'Legendary' },
  mythic: { color: '#EF4444', label: 'Mythic' },
};

/**
 * Get achievements by category
 * @param {string} category - Category name
 * @returns {array} Achievements in category
 */
export const getAchievementsByCategory = (category) => {
  return ACHIEVEMENTS.filter((a) => a.category === category);
};

/**
 * Get achievement by ID
 * @param {string} id - Achievement ID
 * @returns {object} Achievement
 */
export const getAchievementById = (id) => {
  return ACHIEVEMENTS.find((a) => a.id === id);
};

/**
 * Get all category names
 * @returns {array} Category names
 */
export const getAllCategories = () => {
  return Object.values(ACHIEVEMENT_CATEGORIES);
};
